name: docker build & push.
on:
  push:
    branches:
     - main
jobs:
  job1:
    name: docker build & push
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@v5.0.0

     - name: docker login
       uses: docker/login-action@v3.5.0
       with: 
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and push Docker images
       uses: docker/build-push-action@v6.18.0
       with:
          context: .
          push: true
          tags: your-dockerhub-username/elearn-frontend:latest


    
          
   